### ISSUE TITLE
feature: add multiple docker-compose profiles for `local` and `prod`

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/actix-web-starter#12]
Currently we have the `actix-server` commented out in the docker compose for simplicity such that a `docker compose up -d` won't start it and error. 

We should just have multiple profiles in the `docker-compose` like `docker compose up -d --local` to start everything but the `actix-server` and vice versa.

**Comment by drew-harris** [comment]
Added this in #11 . The actix server will not start by default and only with: `docker compose up --profile prod up`. I don't think "local" is necessary because it would be the same as the default behavior, but if you want me to add it let me know.
