### ISSUE TITLE
feature: add CI action for updating the `generated-openapi-client`

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/actix-web-starter#13]
After any PR which modifies the `server` files, we should regenerate the client.

**Comment by drew-harris** [comment]
https://github.com/marketplace/actions/github-action-for-committing-changes-to-a-repository
@skeptrunedev is this the type of thing you would want to use? what stage of the PR should it apply the changes, every push (if its out of sync), or on the merge as an amended rebase or something?
